### ISSUE TITLE
Support imports

### ISSUE THREAD

**Issue by birbilis** [iamazeem/proto-convert#2]
Is proto-convert able to handle import in proto files?

**Comment by iamazeem** [comment]
Like this?

https://github.com/iamazeem/protobuf-log-sample/blob/6fb30653e595629cead29a26db03f55ce5590e5e/log.proto#L5

---

Test run with [log.proto](https://raw.githubusercontent.com/iamazeem/protobuf-log-sample/6fb30653e595629cead29a26db03f55ce5590e5e/log.proto) and [log.bin](https://raw.githubusercontent.com/iamazeem/protobuf-log-sample/main/log.bin):

```text
$ proto-convert -m b2j -p ./log.proto -t service.logging.Log -i ./log.bin -o log.json
>> [B] ./log.bin (86 bytes)
<< [J] log.json (183 bytes)

$ cat ./log.json | jq .
{
  "context": {
    "timestamp": "2020-06-01T16:24:19Z",
    "hostOrIp": "192.168.xxx.xxx",
    "serviceName": "test",
    "user": "test"
  },
  "level": "INFO",
  "message": "This is a test log generated by [./log.rb]."
}
```

Please test with your proto files that include `import` directives.
Let me know if you face any issues.

**Comment by pawelantczak** [comment]
Hello.

With very similar proto file, we are facing below issue.

```Types.proto``` file:

```
syntax = "proto3";

package net.sample;

import "google/protobuf/any.proto";

option java_multiple_files = true;

message Type {
  string traceId = 1;
  google.protobuf.Any header = 2;
  google.protobuf.Any body = 3;
}
```

```test.json``` file:
```
{
  "traceId": "2",
  "header": {},
  "body": {},
}
```
Results:
```
./proto-convert -m j2b -p Types.proto -t net.sample.Type -i test.json -o test.bin

Possible 'import' issue! Use a single self-contianed .proto file! cannot load such file -- google/protobuf
```

**Comment by birbilis** [comment]
Looking at the code that error message it's here:
https://github.com/iamazeem/proto-convert/blob/77ed15facc343191e9a3a0e80f9d5581c1e65a6d/bin/proto-convert#L182

btw, has a typo there, it's "self-contained", not "self-contianed" it should say. Plus it could say "Try" instead of "Use" if that is just a suggestion for cases where the importing failed for someother reason (can't it show some msg for that reason?) and the tool does support imports

**Comment by birbilis** [comment]
Another thing I was looking for was how it uses "proto_path" command-line param of protoc, seems it's being used here:
https://github.com/iamazeem/proto-convert/blob/77ed15facc343191e9a3a0e80f9d5581c1e65a6d/bin/proto-convert#L45

from what I understand it tries to use the folder of the passed-in file as the root folder. But that will be a relative path and not sure if protoc compiler treats such relative paths as relative to its own folder.

file_dir is set a little above in the code, at:
https://github.com/iamazeem/proto-convert/blob/77ed15facc343191e9a3a0e80f9d5581c1e65a6d/bin/proto-convert#L43

Maybe should use an absolute path there, that is:
`file_dir = File.expand_path(File.dirname(file_path))`

see the replies at:
https://stackoverflow.com/questions/15358669/confusing-behavior-of-file-dirname
and related doc:
https://ruby-doc.org/core-2.0.0/File.html#method-c-expand_path
seems this will also support "~" :

> The given pathname may start with a “~'', which expands to the process owner's home directory (the environment variable HOME must be set correctly). “~user'' expands to the named user's home directory.

**Comment by iamazeem** [comment]
> ```
> ./proto-convert -m j2b -p Types.proto -t net.sample.Type -i test.json -o test.bin
> 
> Possible 'import' issue! Use a single self-contianed .proto file! cannot load such file -- google/protobuf
> ```

@pawelantczak 

Hi,

Looks like `protoc` was not able to find the `google/protobuf`:

```text
cannot load such file -- google/protobuf
```

Please make sure that the files from the `include` folder are available.
There's no information about your environment so I won't be able to suggest anything.

On my Ubuntu 18.04 machine, the installed paths are:

```text
/usr/local/bin/protoc
/usr/local/include/google/protobuf/
```

Once installed, it should work.
I tested with your proto and it was compiled successfully.
However, I'm observing another issue with the `protobuf` itself.
Please test on your side and let me know if there's anything.
I'd appreciate it if you could open a separate issue for that one.

Thanks!

**Comment by iamazeem** [comment]
> Looking at the code that error message it's here:
> https://github.com/iamazeem/proto-convert/blob/77ed15facc343191e9a3a0e80f9d5581c1e65a6d/bin/proto-convert#L182
> 
> btw, has a typo there, it's "self-contained", not "self-contianed" it should say. Plus it could say "Try" instead of "Use" if that is just a suggestion for cases where the importing failed for someother reason (can't it show some msg for that reason?) and the tool does support imports

@birbilis 

Good catch, thanks!

The message was mainly added for the recursive `import` cases.
For the reason part, the `ERROR_INFO` is being printed also.

https://github.com/iamazeem/proto-convert/blob/77ed15facc343191e9a3a0e80f9d5581c1e65a6d/bin/proto-convert#L182

I'm thinking about changing it only to:

```text
LoadError: #{$ERROR_INFO}
```

For recursive cases, the error returned by `protoc` will be printed.

What do you think?

**Comment by iamazeem** [comment]
@birbilis 

Regarding your comment about `--proto_path`, please see:

https://github.com/iamazeem/proto-convert/blob/77ed15facc343191e9a3a0e80f9d5581c1e65a6d/bin/proto-convert#L42-L45

Please test it on your side with relative and absolute paths.
Let me know if you observe any discrepancies.
