### ISSUE TITLE
cannot load such file -- google/protobuf

### ISSUE THREAD

**Issue by pawelantczak** [iamazeem/proto-convert#3]
Hello.

It seems that there is problem with importing Google types.

I'm using latest macos with protobuf installed via ```brew install protobuf```
I've also tried on Ubuntu 18.04 copying includes folder to ```/usr/local/include/google/protobuf/``` 
Results are the same.

```
git clone https://github.com/iamazeem/proto-convert.git
cd proto-convert/test
../bin/proto-convert -m j2b -p test.proto -t test.Message -i test.json -o test.bin
Possible 'import' issue! Use a single self-contianed .proto file! cannot load such file -- google/protobuf
```

```
ls -la  /usr/local/include/google/protobuf/
total 4072
drwxr-xr-x  71 krr  admin    2272 Jun  8 16:15 .
drwxr-xr-x   3 krr  admin      96 Jun  8 16:15 ..
-rw-r--r--   1 krr  admin    6365 Jun  8 16:15 any.h
-rw-r--r--   1 krr  admin   14209 Jun  8 16:15 any.pb.h
-rw-r--r--   1 krr  admin    5916 Jun  8 16:15 any.proto
```

**Comment by iamazeem** [comment]
Hi,

Please run `protoc` where `Types.proto` is located and share the output:

```bash
protoc --ruby_out=. --proto_path=. ./Types.proto
```

**Comment by pawelantczak** [comment]
```
protoc --ruby_out=. --proto_path=. ./test.proto


ll
total 32
-rw-r--r--  1 krr  staff     8B Jul  8 09:00 test.bin
-rw-r--r--  1 krr  staff    24B Jul  8 09:00 test.json
-rw-r--r--  1 krr  staff    94B Jul  8 09:00 test.proto
-rw-r--r--  1 krr  staff   439B Jul  8 10:13 test_pb.rb


cat test_pb.rb
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("test.proto", :syntax => :proto3) do
    add_message "test.Message" do
      optional :id, :int32, 1
      optional :body, :string, 2
    end
  end
end

module Test
  Message = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("test.Message").msgclass
end
```

**Comment by iamazeem** [comment]
Please try your `Types.proto` file with `protoc`.

**Comment by pawelantczak** [comment]
No errors, file generated. 
```
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Types.proto

require 'google/protobuf'

require 'google/protobuf/any_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("Types.proto", :syntax => :proto3) do
    add_message "net.sample.Type" do
      optional :traceId, :string, 1
      optional :header, :message, 2, "google.protobuf.Any"
      optional :body, :message, 3, "google.protobuf.Any"
    end
  end
end

module Net
  module Sample
    Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("net.sample.Type").msgclass
  end
end
```

**Comment by iamazeem** [comment]
That's strange.
It works on my side with `proto-convert` as well.
But, when you do, it doesn't, right?

Please share the output of:

```bash
proto-convert -v
```

**Comment by pawelantczak** [comment]
Unfortunately it doesn't. Even with files from your ```test``` directory (as illustrated in first post). 

```
./proto-convert 0.2.0
Author: Azeem Sajid <azeem.sajid@gmail.com>
GitHub: https://github.com/iamAzeem/proto-convert
```

**Comment by iamazeem** [comment]
Right.
Why is it showing `./proto-convert`?
Did you not install it via `sudo gem install proto-convert` command i.e. running it from its own directory?

I see now what that `google/protobuf` error means.
`proto-convert` has a dependency on `google-protobuf` gem.
https://github.com/iamazeem/proto-convert/blob/52f490f2e27314c13752ab273893347e19a81203/proto-convert.gemspec#L21

You need to install this dependency manually or install `proto-convert` with `sudo gem install proto-convert` and its dependencies will be installed with it.

**Comment by pawelantczak** [comment]
Yep. Mystery solved. When I saw bin folder I though that this is a standalone executable. Sorry for bothering you and thank you for your time.

**Comment by iamazeem** [comment]
Hopefully, after installing it properly, your issue will be resolved.
In addition, I have also added test files containing `import` directive (https://github.com/iamazeem/proto-convert/tree/main/test).
Also, I have added `macOS` as a test platform in the [CI workflow](https://github.com/iamazeem/proto-convert/blob/main/.github/workflows/ci.yml) and all the tests are passing.

See the CI test run for Ubuntu 18.04, Ubuntu 20.04 and macOS 10.15:
https://github.com/iamazeem/proto-convert/actions/runs/1011088394
