### ISSUE TITLE
Can we convert .proto file which implicitly call many .proto file?

### ISSUE THREAD

**Issue by ParimalaPeriyasamy** [iamazeem/proto-convert#4]
I'm trying to convert my .proto file into binary format tp import converted binay file i6n postman to test with http put call. Over all to test .proto files with http call. But my main .proto files calling many .proto files to get messages? What should i change in the mentioned command? I'm raising it in issue, since i couldn't find other way to reach you?

**Comment by iamazeem** [comment]
Did you try it for your use case including multiple proto files?
Please share the errors if you've got any.

If you could share a minimal reproducible example that'd be helpful to reproduce this on my side.
