### ISSUE TITLE
[Feature] Handle nested/imported proto files with a command-line flag

### ISSUE THREAD

**Issue by sergio239new** [iamazeem/proto-convert#5]
If i try to convert to json using a proto file that contains import of the other proto file, this will bring error: proto file was not found or had errors..
To fix this, the protoc call must contain a special parameter --proto_path or -I with the path to search for other proto files..
This means, that this path, please, must be added to proto-convert as an additional parameter and used then in the internal protoc call..

**Comment by iamazeem** [comment]
Hi @sergio239new,

Thank you for reporting this!

Adding a `--proto_path` flag seems plausible.
But, what if there are multiple paths?
What do you think whether this flag should handle a single or multiple paths?

If you could attach some sample files with steps to reproduce this, that would be great.
I would be able to test and iterate on this much faster. Thanks!

**Comment by sergio239new** [comment]
Hi,

to your question, according Google docs: "Multiple import directories can be specified **by passing the --proto_path option multiple times**"
Maybe same option for proto-convert ?

.. and sorry, can't publish a sample, because of restrictions, is for work..

**Comment by iamazeem** [comment]
Yes, that's what I was thinking about.

Regarding samples, no worries.
I'll handle that. Thank you! :+1:

**Comment by iamazeem** [comment]
@sergio239new

I've spent some time on it and found out that to make this fully work `protoc` is required to generate code for all the dependencies (imported proto files) which it, at the moment, does not. Without code generation for the dependencies, `proto-convert` won't be able to work as it needs to have those available to translate messages.

If you have any suggestions on this, please do let me know. Thanks!
